---
abstract: 'class to talk to MPD (Music Player Daemon) servers'
author:
  - 'Jerome Quelin'
generated_by: 'Dist::Zilla version 1.092680'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-MPD
provides:
  Audio::MPD:
    file: lib/Audio/MPD.pm
    version: 0.19.9
  Audio::MPD::Collection:
    file: lib/Audio/MPD/Collection.pm
    version: 0.19.9
  Audio::MPD::Playlist:
    file: lib/Audio/MPD/Playlist.pm
    version: 0.19.9
requires:
  DB_File: 0
  Data::Dumper: 0
  Encode: 0
  English: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  Getopt::Euclid: 0
  IO::Socket: 0
  Module::Build: 0
  Proc::Daemon: 0
  Readonly: 0
  Scalar::Util: 0
  Test::Corpus::Audio::MPD: 1.092900
  Test::More: 0
  Time::HiRes: 0
  base: 0
  constant: 0
  perl: 5.008
resources:
  MailingList: http://groups.google.com/group/audio-mpd
  homepage: http://search.cpan.org/dist/Audio-MPD
  repository: http://github.com/jquelin/audio-mpd
version: 0.19.9
